server:
  port: 3344

spring:
  application:
    name: cloud-17-config-3344 #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MuziMin0222/muzimin-spring-cloud-study.git #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - cloud-18-config-files
      label: main #读取分支
      #启动成功后访问的路径 http://ip:3344/{label}/{application}-{profile}.yml 能访问的配置文件 就表示成功了
    #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 15672
    username: root
    password: 123456

# eureka的客户端配置
eureka:
  client:
    # 表示是否将自己注册进eurekaserver，默认为true
    register-with-eureka: true
    # 是否从eureka中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      ## 单机版
      #defaultZone: http://localhost:7001/eureka/
      ##集群版
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7001/eureka/
  instance:
    instance-id: cloud-17-config-3344
    prefer-ip-address: true  #访问路径可以显示IP地址
    # eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30S）
    lease-renewal-interval-in-seconds: 1
    # eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90S），超时将会剔除服务
    lease-expiration-duration-in-seconds: 2

##rabbitmq相关配置,暴露bus刷新配置的端点 SpringCloud Bus动态刷新全局广播
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'