server:
  port: 8002

spring:
  application:
    name: cloud-01-payment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.muzimin.entity


## eureka的客户端配置
eureka:
  client:
    # 表示是否将自己注册进eurekaserver，默认为true
    register-with-eureka: true
    # 是否从eureka中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      ## 单机版
      #defaultZone: http://localhost:7001/eureka/
      ##集群版
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7001/eureka/