server:
  port: 9527

spring:
  application:
    name: cloud-16-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-01-PAYMENT            # lb://在注册中心对应的服务名称
          predicates:
            - Path=/payment/select/**         # 断言，路径相匹配的进行路由
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-01-PAYMENT            # lb://在注册中心对应的服务名称
          predicates:
            - Path=/payment/discover/**         # 断言，路径相匹配的进行路由

## eureka的客户端配置
eureka:
  client:
    # 表示是否将自己注册进eurekaserver，默认为true
    register-with-eureka: true
    # 是否从eureka中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      ## 单机版
      #defaultZone: http://localhost:7001/eureka/
      ##集群版
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7001/eureka/
  instance:
    instance-id: cloud-16-gateway-9527
    prefer-ip-address: true  #访问路径可以显示IP地址
    # eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30S）
    lease-renewal-interval-in-seconds: 1
    # eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90S），超时将会剔除服务
    lease-expiration-duration-in-seconds: 2